tryyang2001/CS3213-Frontend-Management-System

frontend/package.json
frontend/src/app/layout.tsx
frontend/src/app/page.tsx
frontend/src/components/common/SideBar.tsx
frontend/src/styles/output.css
frontend/tailwind.config.ts
frontend/yarn.lock

Modify layout and create sidebar

---

postman/user-microservice-postman-requests

Add Postman folder and json postman file for user-microservice as a API requests sample

Postman json file for user microservice

---

backend/assignment-service/ATTRIBUTIONS.md
backend/assignment-service/README.md
backend/assignment-service/package.json
backend/grading-service/ATTRIBUTIONS.md
backend/grading-service/README.md
backend/grading-service/package.json
backend/grading-service/yarn.lock
frontend/ATTRIBUTIONS.md
frontend/README.md

Created README.md to ease setting up individual service locally. Also created an ATTRIBUTIONS.md to credit those code imported from external sources. Last but not least, updated backend node scripts to ensure the schema types are pre-generated before building or running the service. Also added a `db` script to show the database records so that we don't need to go to supabase to see.
Above shows an example of running `yarn db` to see the database records.

Create README, ATTRIBUTIONS markdown files in individual service and update scripts

---

backend/README.md
frontend/README.md

Add github actions badges

---

frontend/src/app/login/page.tsx
frontend/src/app/sign-up/page.tsx
frontend/src/helpers/assignment-service/api-wrapper.ts

I made some mistakes when trying to adhere to the new rules, this caused some bugs
- `() => void(async () => ...)` doesn't work at all
- Fix: Changed to `() => void asyncFunction()` which i can confirm works
- To make ensure `no_unused_var` was adhered to, i left `_response = await api` in `api-wrapper.ts`, this caused the frontend to crash when called as there is no error handling.
- Fix: Added error handling

Fix bugs caused by bad adherence to rules

---

backend/grading-service/jest.config.js
backend/grading-service/package.json
backend/grading-service/src/controllers/base-controller.ts
backend/grading-service/src/controllers/grading-controller.ts
backend/grading-service/src/libs/utils/errorUtils.ts
backend/grading-service/src/libs/validators/get-submission-query-validator.ts
backend/grading-service/src/libs/validators/post-feedback-validator.ts
backend/grading-service/src/libs/validators/post-parser-validator.ts
backend/grading-service/src/middlewares/cors.ts
backend/grading-service/src/models/its/error-feedback.ts
backend/grading-service/src/services/get-handler.ts
backend/grading-service/src/tests/payloads/student-code.ts
backend/grading-service/src/tests/unit/base-controller.test.ts
backend/grading-service/src/tests/unit/cors.test.ts
backend/grading-service/src/tests/unit/get-handler.test.ts
backend/grading-service/src/tests/unit/grading-controller.test.ts
backend/grading-service/src/tests/utils/create-test-server-utils.ts
backend/grading-service/yarn.lock

Create more unit tests for controllers including the `base-controller` and the `grading-controller`, as well as the `get-handler` and `cors`. 
Closes #45 
In overall, the line coverage is 98.93%, with 89.65% branch coverage, which is more than sufficient for the requirement (I hope)

Create Unit Tests for `controllers` and `cors` for Grading Service 

---

backend/assignment-service/jest.config.js
backend/assignment-service/package.json
backend/assignment-service/src/controllers/assignment-controller.ts
backend/assignment-service/src/controllers/base-controller.ts
backend/assignment-service/src/libs/utils/error-message-utils.ts
backend/assignment-service/src/libs/validators/assignments/create-assignment-validator.ts
backend/assignment-service/src/libs/validators/assignments/update-assignment-validator.ts
backend/assignment-service/src/services/assignments/delete-handler.ts
backend/assignment-service/src/tests/payloads/requests/assignments/create-assignment-request-body.ts
backend/assignment-service/src/tests/payloads/requests/assignments/update-assignment-request-body.ts
backend/assignment-service/src/tests/payloads/requests/create-assignment-payload.json
backend/assignment-service/src/tests/payloads/requests/index.ts
backend/assignment-service/src/tests/payloads/responses/assignments/get-assignment-by-id-response.ts
backend/assignment-service/src/tests/payloads/responses/assignments/get-created-assignment-response.ts
backend/assignment-service/src/tests/payloads/responses/assignments/get-updated-assignment-response.ts
backend/assignment-service/src/tests/payloads/responses/index.ts
backend/assignment-service/src/tests/unit/assignments/create-assignment.test.ts
backend/assignment-service/src/tests/unit/assignments/delete-assignment-by-id.test.ts
backend/assignment-service/src/tests/unit/assignments/get-assignment-by-id.test.ts
backend/assignment-service/src/tests/unit/assignments/get-assignment-by-user-id.test.ts
backend/assignment-service/src/tests/unit/assignments/update-assignment-by-id.test.ts
backend/assignment-service/src/tests/unit/base-controller.test.ts
backend/assignment-service/src/tests/unit/cors.test.ts
backend/assignment-service/src/tests/utils/create-test-server-utils.ts
backend/grading-service/package.json

As assignment service has 2 main components: assignment and questions, I decided to write unit tests for assignment component first. It is very time-consuming TT. I hope the coverage is satisfying, I think I managed to reach 90+% test coverage for all the assignment controllers and handlers. 
This is part of the work for assignment service unit tests.
As you can see here, coverage for `assignment-controller`, `libs/validators/assignments`, `middlewares`, and `services/assignments` all have 80-100%.

(Part 1) Create unit tests for `assignment-controller`, `assignment handlers`, `base-controller`, and `cors` in Assignment Service

---

frontend/src/app/__tests__/__snapshots__/pages.test.tsx.snap
frontend/src/app/__tests__/pages.test.tsx
frontend/src/components/forms/FileInput.tsx
frontend/src/components/forms/ProfileEditor.tsx
frontend/src/components/forms/__tests__/AccountEditor.test.tsx
frontend/src/components/forms/__tests__/FileInput.test.tsx
frontend/src/components/forms/__tests__/PasswordInput.test.tsx
frontend/src/components/forms/__tests__/ProfileEditor.test.tsx

Removes the ACT warnings by using `await` to expect the updated changes to the page

Remove ACT warnings in tests

---

backend/grading-service/package.json
backend/grading-service/src/app.ts
backend/grading-service/src/libs/docs/swagger.yaml
backend/grading-service/src/libs/utils/swagger-utils.ts
backend/grading-service/src/routes/docs/index.ts
backend/grading-service/src/routes/route.ts
backend/grading-service/yarn.lock

Create API documentation for grading service
Closes #67

Create API documentation for grading service

---

backend/assignment-service/src/controllers/assignment-controller.ts
backend/assignment-service/src/libs/validators/assignments/get-assignments-validator.ts
backend/assignment-service/src/services/assignments/get-handler.ts
backend/assignment-service/src/tests/unit/assignments/get-assignments-by-user-id.test.ts
frontend/src/app/__tests__/__snapshots__/pages.test.tsx.snap
frontend/src/app/assignments/[id]/edit/page.tsx
frontend/src/app/assignments/create/page.tsx
frontend/src/app/dashboard/page.tsx
frontend/src/app/login/page.tsx
frontend/src/app/sign-up/page.tsx
frontend/src/components/assignment/create/AssignmentEditor.tsx
frontend/src/components/common/Icons.tsx
frontend/src/components/common/SideBar.tsx
frontend/src/components/common/UserDropdown.tsx
frontend/src/helpers/assignment-service/api-wrapper.ts
frontend/src/helpers/user-service/api-wrapper.ts

As we discussed earlier, all users will see all assignments by following these rules:
1. tutor can see all published and unpublished assignments
2. students can only see all published assignments
3. none of the user type can see expired assignments, but this is easily extendable should we want this feature. Nonetheless, this has no impact to get submission in grading.
Also, a student should not be able to create an assignment, so I disable the access to such page if the user role is "student".
Lastly, the log out doesn't correctly remove the "token" cookie, so a logged out user can still access other pages. I have fixed this problem in this PR as well.

Update getAssignments endpoint and fix frontend bugs

---

frontend/src/app/assignments/[id]/page.tsx
frontend/src/helpers/grading-service/api-wrapper.ts

Allow students to submit their code by uploading files.
#49 
Old PRs: #62 #74
Error with usage of FileUpload / implementation of handleSubmitAssignment, toast appearing as soon as I click Choose File:

Integrate grading service with frontend (part 2) – submit code and post feedback (student)

---

frontend/src/app/assignments/[id]/page.tsx
frontend/src/types/grading-service.d.ts

This PR should fix the problem where when the user click the submit code button, an error toast appears.

Fix code submission bug

---

backend/user-service/Dockerfile
frontend/Dockerfile
k8s/startup.yaml

Fix Dockerfile

---

backend/grading-service/Dockerfile
backend/grading-service/package.json

Fix grading service package json build script for deployment

---

backend/assignment-service/Dockerfile
backend/assignment-service/package.json

Fix assignment-service dockerfile

---

k8s/startup.yaml

Change ACR address in k8s manifest file

---

k8s/startup.yaml

Fix manifest files user service tag

---

frontend/src/components/assignment/AssignmentList.tsx

Last few fixes for UI
NIL
Fix chips display:

Final UI fixes

---

.github/workflows/Backend_CI.yml
.github/workflows/Overall_CI.yml
.github/workflows/frontend_CI.yml

My bad, i forgot to set the github action permissions. This should work now.

Fix missing permissions for actions

---

backend/user-service/Dockerfile
frontend/Dockerfile
nginx/default.conf

Fix deployment client-side error

---

frontend/package.json
frontend/src/app/assignments/[id]/edit/page.tsx
frontend/src/app/assignments/[id]/questions/create/page.tsx
frontend/src/app/assignments/submissions/page.tsx
frontend/src/components/assignment/create/TestCasesInput.tsx
frontend/yarn.lock

Change crypto.randomUUID() to uuidv4() from uuid

---

README.md
backend/assignment-service/README.md
backend/grading-service/README.md
backend/user-service/README.md
frontend/README.md

Add instructions to run each services and run whole project using Docker Engine in README.md
